### ISSUE TITLE
Errors on Godot 4.0.2

### ISSUE THREAD

**Issue by Yuri-Snitko** [Shidoengie/FPS-template-gd4#2]
It doesn't work on Godot 4.0.2

E 0:00:01:0290   load_source_code: Attempt to open script 'res://Global/Settings.gd' resulted in error 'File not found'.
  <C++ Error>    Condition "err" is true. Returning: err
  <C++ Source>   modules/gdscript/gdscript.cpp:1045 @ load_source_code()

E 0:00:01:0290   start: Script does not inherit from Node: res://Global/Settings.gd.
  <C++ Error>    Condition "!valid_type" is true. Continuing.
  <C++ Source>   main/main.cpp:2776 @ start()

Also basic_block.gd:

Line 72:Cannot infer the type of "texture_folder" variable because the value doesn't have a set type.
Line 73:Cannot infer the type of "full_texture_path" variable because the value doesn't have a set type.

**Comment by TheMemeSniper** [comment]
having this issue too 😬

**Comment by TheMemeSniper** [comment]
it seems #1 wasn't pushed to godotengine.org

**Comment by Shidoengie** [comment]
oh
